spring:
  application:
    name: ela
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://${DB_URL:localhost:1521}/${DB_PATH:test};OLD_INFORMATION_SCHEMA=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS ELASTIC_TEST\;SET SCHEMA ELASTIC_TEST
    username: ${DB_USER:sa}
    password: ${DB_PASSWD:}
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  h2:
    console:
      enabled: false
      path: /h2-console
  elasticsearch:
    uris: localhost:9300
    username: elastic
    password: changeme
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: info
    org.springframework.data.elasticsearch.client.WIRE: trace